### ISSUE TITLE
Honda DBC cleanup

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/opendbc#496]
Ideally, we can use a single DBC for all Hondas, like we do with many of the more recent car ports. This can be done incrementally by doing the following:
* merging DBCs
* using common, universal signals when possible
* abstracting out repeated definitions into common DBCs

**Comment by sshane** [comment]
- [ ] See if `LAT_ACCEL` under `KINEMATICS` on 145 is also available on 148 for cars using 145. The LAT_ACCEL signal is defined in the same location in the message
- [ ] Fix duplicate gear signals defined
- [ ] A lot of these messages are common in bosch vehicles, possible unify:
  - [ ] DOORS_STATUS
  - [ ] STANDSTILL
  - [ ] GEARBOX
  - [ ] GAS_PEDAL_2

**Comment by sshane** [comment]
Notes about common signals:

-  [ ] `DOORS_STATUS`:
  - Identical: `honda_civic_hatchback_ex_2017_can`, `honda_civic_sedan_16_diesel_2019_can`, `honda_crv_ex_2017_can`, `honda_insight_ex_2019_can`
  - Missing (using `SCM_FEEDBACK`): `honda_crv_hybrid_2019_can`, `honda_accord_2018_can`, `acura_rdx_2020_can`
- [ ] `GAS_PEDAL_2`: Not used in openpilot
- [ ] `STEERING_CONTROL`:

Common messages:

- [ ] Common for _bosch_2020 and _honda_2017: `VSA_STATUS`, `STEER_MOTOR_TORQUE`, `STANDSTILL`, `ENGINE_DATA`, `POWERTRAIN_DATA`, `WHEEL_SPEEDS`, `VEHICLE_DYNAMICS`

- [ ] Common for `_bosch_2020` and `_bosch_2018`: `ADJACENT_RIGHT_LANE_LINE_2`, `KINEMATICS`, `STEERING_CONTROL`, `BOSCH_SUPPLEMENTAL_1`, `BRAKE_HOLD`, `ENGINE_DATA`, `POWERTRAIN_DATA`, `STEER_STATUS`, `VSA_STATUS`, `EPB_STATUS`, `VEHICLE_DYNAMICS`, `LEFT_LANE_LINE_1`, `LEFT_LANE_LINE_2`, `RIGHT_LANE_LINE_1`, `RIGHT_LANE_LINE_2`, `ADJACENT_LEFT_LANE_LINE_1`, `ADJACENT_LEFT_LANE_LINE_2`, `ADJACENT_RIGHT_LANE_LINE_1`, `ADJACENT_RIGHT_LANE_LINE_2`, `SCM_BUTTONS`, `CAR_SPEED`, `ACC_HUD`, `CRUISE`, `SCM_FEEDBACK`, `CAMERA_MESSAGES`, `STALK_STATUS`, `STALK_STATUS_2`, `XXX_16`

- [x] Common between all base DBCs (but not all use/would cause superset): `ACC_CONTROL`, `ACC_CONTROL_ON`,

- [x] Common between all base DBCs: `STEER_MOTOR_TORQUE`, `WHEEL_SPEEDS`, `ROUGH_WHEEL_SPEED`, `SEATBELT_STATUS`, `LKAS_HUD`

**Comment by jyoung8607** [comment]
Bringing Shane's notes up-to-date with work he's already done.

**Already consolidated**
* `[ADJACENT_|][LEFT|RIGHT]_LANE_LINE_[1|2]`
* `ACC_HUD`
* `BOSCH_SUPPLEMENTAL_1`
* `BRAKE_HOLD`
* `CAMERA_MESSAGES`
* `CAR_SPEED`
* `CRUISE`
* `DOORS_STATUS`
* `ENGINE_DATA`
* `GAS_PEDAL_2`
* `KINEMATICS`
* `POWERTRAIN_DATA`
* `ROUGH_WHEEL_SPEED`
* `SEATBELT_STATUS`
* `STALK_STATUS[|_2]`
* `STEERING_CONTROL`
* `STEER_MOTOR_TORQUE`
* `VEHICLE_DYNAMICS`
* `VSA_STATUS`
* `WHEEL_SPEEDS`
* `XXX_16`

**Possible cleanup opportunities**
- [x] `ACC_CONTROL[|_ON]` (looks like a copy escaped into honda_pilot_2023)
  * Honda Pilot has an ACC_CONTROL/LKAS_HUD combo that, if verified correct, needs a generator refactor
- [x] `BRAKE_MODULE` #2483
- [x] `EPB_STATUS` #2458
- [x] `GEARBOX` #2457 
  - [x] `BO_ 392` becomes GEARBOX_AUTO in the ACURA_RDX DBC
  - [x] `BO_ 401` becomes GEARBOX_CVT shared across Honda
  - [x] `BO_ 419` becomes GEARBOX_AUTO shared across Honda
  - [x] `BO_ 477` for manual transmissions goes away, switching to reverse detection only
- [x] `LKAS_HUD` (some extra copies of 829, verify they're identical)
- [x] `SCM_BUTTONS` / `SCM_FEEDBACK` #2482 
  - [x] `BO_ 422` / `BO_ 660` is Nidec specific, moves to _nidec_scm_group_a
  - [x] `BO_ 662` / `BO_ 806` is Nidec/Bosch shared, moves to _nidec_scm_group_b
- [x] `STANDSTILL` #2464 (still a possible bug on Insight)
- [x] `STEER_STATUS`
  - [x] `BO_ 399` length 6 #2735
  - [x] `BO_ 399` length 7 #2485
- [x] `STEERING_CONTROL` (last dupe removed in #2469)

**Comment by adeebshihadeh** [comment]
>     * [ ]  `BO_ 399` length 6* [ ]  `BO_ 399` length 7[x]

If this is real, it would be nice if the CANParser supported picking the right one with both present in the DBC. Also relevant: https://github.com/commaai/opendbc/issues/574.

**Comment by jyoung8607** [comment]
More cleanup:

* #2736
* #2737
* #2743

We have 16 generated Honda DBCs. At this stage of refactoring, 9 of them now consist only of generator includes and several are exact duplicates. With just a little more cleanup we'll be ready to collapse many of them.

**Comment by jyoung8607** [comment]
Resolving: with #2744 as the capstone, we've reached a state reasonably close to optimal.

I've a suspicion the one unique thing in the Insight DBC isn't real, but I'll cross that bridge when working the longitudinal backlog.
